version: '3'
services:
    redis:
        restart: always
        image: redis:alpine
    video:
        build: .
        # ports:
        #     - "8080:8080"
        restart: unless-stopped
        depends_on:
            - "redis"
        volumes: 
          - ./video_transcode/config:/opt/video_transcode/config